PATH=C:\SERVIDOR\UTIL;\UTIL;C:\SERVIDOR\CLIPPER\CLIP53\BIN;C:\UTIL;C:\WINDOWS\SYSTEM32
SET INCLUDE=C:\SERVIDOR\CLIPPER\CLIP53\INCLUDE
SET LIB=C:\SERVIDOR\CLIPPER\CLIP53\LIB
SET OBJ=C:\SERVIDOR\CLIPPER\CLIP53\OBJ
SET TMP=C:\
