COPY VPCEI1U2.EXE C:\VPPRG\VP\VPNOVO\VPCEI1U1.EXE
COPY VPCEI1U2.EXE C:\VPPRG\VP\VPNOVO\VPCEI1U2.EXE
COPY VPCEI1U2.EXE C:\VPPRG\VP\VPNOVO\VPCEI1U3.EXE
COPY VPCEI1U2.EXE C:\VPPRG\VP\VPNOVO\VPCEI1U4.EXE
COPY VPCEI1U2.EXE C:\VPPRG\VP\VPNOVO\VPCEI1U5.EXE
COPY VPCEI1U2.EXE C:\VPPRG\VP\VPNOVO\VPCEI1U6.EXE
