@ECHO OFF
REM IF EXIST \POINTER\53.PAR GOTO CONT
REM IF EXIST \POINTER\53X.PAR GOTO CONT

CLS
REM ECHO.
REM ECHO. O Clipper n„o est  na vers„o correta : v5.3!
REM ECHO.
REM GOTO FIM

:CONT
rem CLIPPER GRUPOS    > C.TXT
rem CLIPPER CONV_VPB >> C.TXT
rem CLIPPER @VPCEI6 > C.TXT
rem CLIPPER @VPCEI7 >> C.TXT
rem CLIPPER VPBIBCEI >> C.TXT
rem CALL LIB
rem CLIPPER NFISCAL >> C.TXT
rem CLIPPER @VPCEI5 > C.TXT

Clipper SWPDV      
Clipper SWPDVSIS
Clipper SWREPORT
Clipper IMP        
Clipper DRIVER
Clipper IMPFIS
Clipper PDVTESTE

TYPE C.TXT

:FIM


