fDepur ("PDV_DEP.TXT", REPL ("Ä", 60), .T.)
//fDepur ("PDV_DEP.TXT", REPL ("Ä", 60), .T.)
//fDepur ("PDV_DEP.TXT", "SWPDV.PRG : 1 : Len( aParcelas ) = [" + STR (Len( aParcelas ), 2) + "]")
  fDepur ("PDV_DEP.TXT", "SWPDV.PRG : 1 : lastkey ()       = [" + STR (LASTKEY (), 3) + "]")
//fDepur ("PDV_DEP.TXT", REPL ("Ä", 60), .T.)
//fDepur ("PDV_DEP.TXT", "SWPDV.PRG : 1 : lastkey ()       = [" + STR (LASTKEY (), 3) + "]")

fDepur ("SWPDV.DEP", REPL ("Ä", 60), .T.)
  fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (nPgtDin, 14, 2) = [" + Str (nPgtDin, 14, 2) + "]")
  fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (nPgtTic, 14, 2) = [" + Str (nPgtTic, 14, 2) + "]")
  fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (nPgtChq, 14, 2) = [" + Str (nPgtChq, 14, 2) + "]")
  fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (nPgtCar, 14, 2) = [" + Str (nPgtCar, 14, 2) + "]")
  fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (nPgtOut, 14, 2) = [" + Str (nPgtOut, 14, 2) + "]")
   fDepur ("SWPDV.DEP", "IMPRIMIU")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ 1 ][ nCnt ][ 1 ], 14, 2) = [" + Str (aMoedas [ 1 ][ nCnt ][ 1 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ 1 ][ nCnt ][ 2 ], 14, 2) = [" + Str (aMoedas [ 1 ][ nCnt ][ 2 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", REPL ("Ä", 60), .T.)
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ 1 ][ nCt ][ 1 ], 14, 2) = [" + Str (aMoedas [ 1 ][ nCt ][ 1 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ 1 ][ nCt ][ 2 ], 14, 2) = [" + Str (aMoedas [ 1 ][ nCt ][ 2 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ 1 ][ nCt ][ 3 ], 14, 2) = [" + Str (aMoedas [ 1 ][ nCt ][ 3 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ 1 ][ nCt ][ 4 ], 14, 2) = [" + Str (aMoedas [ 1 ][ nCt ][ 4 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ 1 ][ nCt ][ 5 ], 14, 2) = [" + Str (aMoedas [ 1 ][ nCt ][ 5 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ nCt ][ 1 ], 14, 2) = [" + Str (aMoedas [ nCt ][ 1 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ nCt ][ 2 ], 14, 2) = [" + Str (aMoedas [ nCt ][ 2 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ nCt ][ 3 ], 14, 2) = [" + Str (aMoedas [ nCt ][ 3 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ nCt ][ 4 ], 14, 2) = [" + Str (aMoedas [ nCt ][ 4 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ nCt ][ 5 ], 14, 2) = [" + Str (aMoedas [ nCt ][ 5 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ 1 ][ nCt ][ 1 ], 14, 2) = [" + Str (aMoedas [ 1 ][ nCt ][ 1 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ 1 ][ nCt ][ 2 ], 14, 2) = [" + Str (aMoedas [ 1 ][ nCt ][ 2 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ 1 ][ nCt ][ 3 ], 14, 2) = [" + Str (aMoedas [ 1 ][ nCt ][ 3 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ 1 ][ nCt ][ 4 ], 14, 2) = [" + Str (aMoedas [ 1 ][ nCt ][ 4 ], 14, 2) + "]")
fDepur ("SWPDV.DEP", "SWPDV.PRG : 1 : Str (aMoedas [ 1 ][ nCt ][ 5 ], 14, 2) = [" + Str (aMoedas [ 1 ][ nCt ][ 5 ], 14, 2) + "]")
