@ECHO OFF

MD MIN
COPY SWPDV.EXE    MIN
COPY PDV.INI      MIN
COPY LOGOTIPO.BMP MIN
COPY FUNDO.BMP    MIN
COPY AGSYSA14.PTX MIN
COPY AGSYSD10.PTX MIN
COPY AGSYSD10.PTX MIN
COPY DGE1609.PTX  MIN
COPY RMN1914.PTX  MIN
COPY VSYS14.PTX   MIN
COPY INFO.EXE     MIN
COPY INFO.PCX     MIN
COPY FUNDORM.PCX  MIN
COPY SIGDRV.SYS   MIN
COPY CONFIG.EXE   MIN
COPY STATUS.EXE   MIN

MD PRG
COPY *.INI        PRG
COPY *.PRG        PRG
COPY *.BAT        PRG
COPY *.INC        PRG
COPY *.TXT        PRG

rem COPY PDVN.INI     PRG
rem COPY PDVB.INI     PRG
rem COPY SWPDV.PRG    PRG
rem COPY C.BAT        PRG
rem COPY L.BAT        PRG
rem COPY E.BAT        PRG
rem COPY F.BAT        PRG
rem COPY CLF.BAT      PRG
rem COPY SAL.BAT      PRG
rem COPY SAL.INC      PRG
rem COPY EDIT.BAT     PRG
rem COPY INST.BAT     PRG
rem COPY INSTALA.BAT  PRG
rem COPY PKUNZIP.EXE  PRG
rem COPY BOXFILL.TXT  PRG
rem COPY LEIA.TXT     PRG
rem COPY PDV.BAT      PRG
rem COPY PDV_VER.BAT  PRG

